# Generated by Django 3.1.1 on 2020-09-16 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reddit', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='songs',
            name='update_on',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
